POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlcGkiLCJpZCI6IjVlYzUyYjcwOWQxZDkzOTBkODU5ZGFhNyIsImlhdCI6MTU4OTk4NzgyMH0.TdpHunAzDriou_5zRoiAoh4MkWvKpPuzduzidxSGcCg

{
    "author": "Teppo Winnipeg",
    "title": "Test title 2",
    "url": "http://google.com/",
    "userId": "5ec52b709d1d9390d859daa7"
}
