POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
content-type: application/json

{
  "type": "HealthCheck",
  "healthCheckRating": "1",
  "description": "Just testing here",
  "date": "2001-02-01",
  "specialist": "Someone"
}